Visual enhancements to TestRunner
beginner-codes/beginner.codes-python pull request #1
Opened 2023-11-10 17:21 UTC by mrrobinhood5

- Option to display description and examples
- Used tables to display result
- added some colors

2023-11-11 02:52 UTC, ZechCodes requested changes

2023-11-11 02:52 UTC, ZechCodes commented on beginnercodes/challenges/test_runner.py
> +def test(challenge: int, solution_func, description: bool = False, examples: bool = False):
Make `solution_func` optional, no need to pass in a function if you just wanna get the description or examples

2023-11-11 02:52 UTC, ZechCodes commented on beginnercodes/challenges/test_runner.py
> +        _r = requests.get(url.replace('XXXX', str(challenge)))
Don't use `replace`, use an f-string (the way it was before)

2023-11-11 02:52 UTC, ZechCodes commented on pyproject.toml
The package version at the top of the file needs to be bumped to 0.1.2

2023-11-11 02:52 UTC, ZechCodes commented on beginnercodes/challenges/test_runner.py
> +    def _fetch_data(url:str) -> Union[Response, str]:
`fetch_data` never returns a string only a `Response`, so the union is unnecessary. This would remove the need for the `Union` import from `typing`.

2023-11-11 02:52 UTC, ZechCodes commented on beginnercodes/challenges/test_runner.py
> +        url = "https://raw.githubusercontent.com/beginner-codes/challenges/main/weekday/test_cases_XXXX.json"
This should be an f-string instead of using `XXXX`

2023-11-11 02:52 UTC, ZechCodes commented on beginnercodes/challenges/test_runner.py
> +        url = "https://raw.githubusercontent.com/beginner-codes/challenges/main/weekday/challenge_XXXX.md"
This should be an f-string instead of using `XXXX`

2023-11-11 02:52 UTC, ZechCodes commented on beginnercodes/challenges/test_runner.py
> +                result += '# ' + info.text.split('# ')[2].replace('#','') if examples else ''
Don't use a ternary if's here. Use `if description` and `elif examples`. Simpler, easier to understand, and results in less op codes to be run.

2023-11-11 17:22 UTC, mrrobinhood5 commented
Added a commit fixing all them things and added 1 more thing in case no function/examples/description args are passed.

2023-12-20 14:51 UTC, ZechCodes commented
Apologies for the extreme delay, all looks good, I’ll merge the changes. Thanks!

2023-12-20 14:52 UTC, merged